#!/bin/bash
#
# A set of common aliases.
#
# Sean Nesdoly
# 2017-08-15

# Common shortcuts
alias rm="rm -i"
alias mv="mv -i"
alias ls="ls --color"
alias ll="ls -lF"
alias g="git"
alias afk="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"

# Always enable colored `grep` output
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# Print each PATH entry on a separate line
alias path='echo -e ${PATH//:/\\n}'

# Correct previous console commands with 'The Fuck' utility
eval $(thefuck --alias)

# Hide/show all desktop icons (useful when presenting)
alias hidedesktop="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
alias showdesktop="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"

# Merge PDF files with a macOS Automator utility
# Usage: `mergepdf -o output.pdf input{1,2,3}.pdf`
# Preferred alternative: ImageMagick's `convert -combine` utility
alias mergepdf='/System/Library/Automator/Combine\ PDF\ Pages.action/Contents/Resources/join.py'
