#!/bin/bash
#
# Define variables for the default shell and all processes that derive from it.
#
# Sean Nesdoly
# 2017-08-15

# Make vim the default editor.
export EDITOR='vim'

# Omit duplicates and commands that begin with a space from history.
export HISTCONTROL='ignoreboth'

# Make Homebrew more secure
export HOMEBREW_NO_INSECURE_REDIRECT=1
export HOMEBREW_CASK_OPTS=--require-sha

# Configure java.
# The precedence of java executables in PATH does not always reflect which JVM
# is selected to run; instead, this seems to be controlled by
# '/usr/libexec/java_home'.
[ -x /usr/libexec/java_home ] && JAVA_HOME=$(/usr/libexec/java_home)
export JAVA_HOME

# Improve searching, squash consecutive blank lines together, and keep screen
# contents after quitting a man page.
export MANPAGER='less -isX'

# Colour bash man pages
export LESS_TERMCAP_mb=$(printf '\e[01;31m') # enter blinking mode - red
export LESS_TERMCAP_md=$(printf '\e[01;35m') # enter double-bright mode - bold, magenta
export LESS_TERMCAP_me=$(printf '\e[0m') # turn off all appearance modes (mb, md, so, us)
export LESS_TERMCAP_se=$(printf '\e[0m') # leave standout mode    
export LESS_TERMCAP_so=$(printf '\e[01;33m') # enter standout mode - yellow
export LESS_TERMCAP_ue=$(printf '\e[0m') # leave underline mode
export LESS_TERMCAP_us=$(printf '\e[04;36m') # enter underline mode - cyan
