#!/bin/bash
#
# ~/.path: Specify the PATH environment variable to tell Unix where to look for
# executables; we append/prepend to it to retain its current value.
#
# On macOS with the Bash shell, this should be sourced from ~/.bash_profile to
# ensure it is picked up in tmux sessions (which execute login shells).
#
# To give an executable precedence in the PATH hierarchy, add its value to the
# start of the string, like so: PATH="/path/to/program:$PATH"
#
# To test for duplicates in your $PATH:
#   echo $PATH | sed 's/:/\n/g' | sort | uniq -c
#
# To check if we are in a tmux session:
#   if [[ -z $TMUX ]]; then
#       echo "We are in tmux!"
#   fi
#
# Sean Nesdoly
# 2021-11-10

# Configure Homebrew, and essential packages installed by it, for the
# appropriate instruction set architecture (x86_64 or arm64).
if [ -x /opt/homebrew/bin/brew ]; then
    # Configure Homebrew for the arm64 architecture
    eval "$(arch -arm64 /opt/homebrew/bin/brew shellenv)"

    # Add GNU utilities as a prefix of PATH, as the macOS versions are outdated
    PATH="$(arch -arm64 brew --prefix gsed)/libexec/gnubin:$PATH"
    PATH="$(arch -arm64 brew --prefix gnu-tar)/libexec/gnubin:$PATH"
    PATH="$(arch -arm64 brew --prefix grep)/libexec/gnubin:$PATH"
    PATH="$(arch -arm64 brew --prefix findutils)/libexec/gnubin:$PATH"
    PATH="$(arch -arm64 brew --prefix coreutils)/libexec/gnubin:$PATH"

    # Python. Override the system default of '/usr/bin/python' (2.7.18).
    PATH="$(arch -arm64 brew --prefix python)/libexec/bin:$PATH"

    # Java
    PATH="$PATH:$(arch -arm64 brew --prefix java)/bin"
elif [ -x /usr/local/bin/brew ]; then
    # Configure Homebrew for the x86_64 architecture
    eval "$(arch -x86_64 /usr/local/bin/brew shellenv)"

    # Add GNU utilities as a prefix of PATH, as the macOS versions are outdated
    PATH="$(arch -x86_64 brew --prefix gsed)/libexec/gnubin:$PATH"
    PATH="$(arch -x86_64 brew --prefix gnu-tar)/libexec/gnubin:$PATH"
    PATH="$(arch -x86_64 brew --prefix grep)/libexec/gnubin:$PATH"
    PATH="$(arch -x86_64 brew --prefix findutils)/libexec/gnubin:$PATH"
    PATH="$(arch -x86_64 brew --prefix coreutils)/libexec/gnubin:$PATH"

    # Python. Override the system default of '/usr/bin/python' (2.7.18).
    PATH="$(arch -x86_64 brew --prefix python)/libexec/bin:$PATH"

    # Java
    PATH="$PATH:$(arch -x86_64 brew --prefix java)/bin"
fi


# ViennaRNA
PATH="$PATH:/usr/local/share/ViennaRNA/bin"

# TMHMM2.0
PATH="$PATH:$HOME/Downloads/software/tmhmm-2.0c/bin"

# Ruby gems
PATH="$PATH:$HOME/.local/share/gem/ruby/3.0.0/bin/"

# Fast Length Adjustment of Short Reads
PATH="$PATH:$HOME/bbme/thesis/libs/FLASH-1.2.11"

export PATH
